DjangoForAll/students

Ritesh-Aggarwal/README.md

Added file README.md as required in Django course L1

Add readme for Ritesh-Aggarwal

---

sidarth/README.md

As part of the Django we were asked to fork this repository and add our own README.md.
This is what my README.md looks like

add: README.md under directory sidarth

---

anuran-roy/README.md

I added my bio to a new directory, keeping in mind all the directions and guidelines.
Files Added:
anuran-roy/README.md
Existing files modified:
NA

Added bio-Anuran Roy

---

kunatastic/readme.md

added readme.md for Kunal kumar jha under kunatastic folder

added Kunatastic student profile

---

M M Kishore/Readme.md

added readme.md into M M Kishore's folder

created M M Kishore -> Readme.md

---

sainAk/README.md

This commit adds the introduction readme for Aakash Singh

Add Aakash Singh

---

akshat-rawat/README.md

This PR has been made for the L1 milestone target of the Django Course.

Add akshat-rawat

---

krishna-sivakumar/README.md

As stated above. 
This PR has been made for the L1 capstone of the Django Course.

Added the Krishna-Sivakumar folder with a README

---

ashesh3/Readme.md

Hey,
This is to add my personal readme into this repository.

Add readme for Ashesh3

---

Aravind-Kannan/README.md

* Added a README.md file for Django course student `Aravind-Kannan`

Add README.md for Aravind-Kannan

---

Pragati1610/Readme.md

Add a readme to describe myself [pragati1610]

docs: create README.md > Pragati Bhattad

---

Rio-Nyx/README.md

Added a new directory with my GitHub username and added a Readme.md file to it

Add Readme for Rahul

---

patelaryan7751/Readme.md

This Folder contains a Readme.md file which contains my bio.

Commited my Bio

---

GokulramGHV/README.md

Created a folder with my user name and added a README.md file.

Added Readme for Gokulram

---

naman114/Readme.md

Added a new directory with my GitHub username and added a Readme.md file to it

Add Readme for naman114

---

rahul-tiwari/README.md

As per part of the Django course here I created a username directory in the root folder along with a readme file inside that.

Added my username directory with readme file

---

Syeda Reeha Quasar/README.md

Added my introduction in markup format in the format provided!

Adding My Introduction to the Student Repo

---

noeljosetp/Readme.md

Added directory noeljosetp which has a Readme.md file where i have added my bio.

Created directory noeljosetp and added a Readme file

---

dheerajroy/Readme.md

Added a new folder 'dheerajroy' which contains a readme file.

Added dheerajroy folder which contains a Readme.md file

---

shivank-kacker/README.md

added myself

---

pratik-londhe4/readme.md

added my readme file

---

pranshu1902/README.md

Hi, I am Pranshu, I have made this change.

Pranshu Aggarwal's commit

---

rithviknishad/README.md

Adds a self-explanatory introduction of [myself](https://github.com/rithviknishad) to `rithviknishad/README.md` that contains my hobbies, interests, technologies used, languages explored and highlight projects.

Adds Rithvik Nishad's README

---

AJgthb2002/README.md

Created a readme.md file inside my directory.
This file contains a few points about myself. They describe my interests & hobbies.

Created my folder containing self-introduction file

---

GanapriyaS/Readme.md

Added Readme for GanapriyaS

---

Aayushi-Mittal/README.md

Added my README file which is formatted in markdown. Completed the task of Django Course Level1. 🚀

Add README for Aayushi

---

Navaneeth/README.md

Added Navaneeth's README file

---

pranshu1902/README.md
sam9111/README.md

PS. I have no idea why there's a change in pranshu's file and I cannot seem to revert it :disappointed:

added README with intro

---

siddnikh/README.md

Added a README file in a folder named siddnikh in the students folder.

Added siddnikh's README file.

---

The-Anton/README.md

add: readme file for The-Anton

---

kshitijv256/Readme.md

GDC batch-3 fellow, Kshitij Verma

Added my Readme.md

---

thedevildude/README.md

added Readme.md for thedevildude

---

konavivekramakrishna/README.md

Add README.md with personal information

---

libinmv/README.md

Change introduces a new folder containing README file for user libinmv

Add README for libinmv

---

Akshay78980/Readme.md

Added readme file containing my personnel details and about the projects I have worked on.
This will be a better addup to the project

Added Readme.md file in Akshay78980 module

---

Ali-elhadi-elzein/README.md

adding me (Ali elhadi elzein) as a new student

adding ali elhadi elzein

---

kihan2518B/Readme.md

Here is the short and quick introduction of my self.

Quick Intro to Kishan

---

nithish1018/Readme.md

Created Readme.md file in a folder with my username with a quick introduction about me as instructed

Added a folder with my username

---

javidsumra/Readme.md

Added a Readme File to Introduce my Self in directory `javidsumra`

Add Quick intro to JavidSumra

---

CharlesRemarks/Readme.md

This is just a basic introduction to who I am.

This is my Introduction to web development sphere!

---

abeeto/README.md

My introduction as part of DjangoForAll

Add README.md for /abeeto (Abhinav Thota)

---

Bichu0077/Readme.md

Added Bichu0077 folder and readme file as a part of the DjangoForAll course.

added Bichu0077
